### ISSUE TITLE
Create HTML Main Structure

### ISSUE THREAD

**Issue by danielkull** [danielkull/FrontM-intro-section-with-dropdown-navigation-main#5]
As basic example:
- Create Header with Navbar
- Create Main
  - With Content Area (H1 and p elements)
  - With Button "Learn more"
  - with Image Area
- Create Footer

**Comment by StefanH87** [comment]
-add Font-Family HTML and CSS
-add color VAR / CSS Stylessheet

-add navbar HTML
  - Main List
  - Sub List
  - Buttons

-add body HTML
  - inkl. Text Content
  - Button
  - Background-Image
  - Client Logos
  
-add footer HTML and pull links inside
